apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    app: broker

spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: confluentinc/cp-kafka
          ports:
            - containerPort: 29092
          envFrom:
            - configMapRef:
                name: kafka-configmap
