apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer

spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: makarovt/kafka-top-producer
          env:
            - name: KAFKA_HOST
              value: "broker:29092"
